/** Helpers for writing project bootstrap files (sites.yml, .gitignore). */

export function contentFolderName(slug: string): string {
  return slug.startsWith("site_") ? slug : `site_${slug}`;
}

export function sitesYmlForEntries(
  entries: { domain: string; contentFolder: string }[],
): string {
  const body = entries
    .map((e) => `${e.domain}:\n  content_folder: ${e.contentFolder}\n`)
    .join("\n");
  return `# Generated by weblify CLI\n${body}`;
}

export function sitesYmlForLocalhost(contentFolder: string): string {
  return sitesYmlForEntries([{ domain: "localhost", contentFolder }]);
}

export function projectGitignore(): string {
  return `.env
.env.local
data/
.cache/
.local/
node_modules/
`;
}
