import fs from "fs";
import os from "os";
import path from "path";
import { afterEach, describe, expect, it } from "vitest";
import { detectProject, listSiteFolders } from "../src/detect";
import { resolveSitesYmlEntries } from "../src/commands/ensure-sites-yml";
import { sitesYmlForEntries } from "../src/lib/project-files";
import type { ResolvedConfig } from "../src/types";

const dirs: string[] = [];

function tmp(): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), "weblify-detect-"));
  dirs.push(d);
  return d;
}

afterEach(() => {
  for (const d of dirs.splice(0)) {
    fs.rmSync(d, { recursive: true, force: true });
  }
});

describe("detectProject", () => {
  it("empty folder", () => {
    const d = tmp();
    expect(detectProject(d).kind).toBe("empty");
  });

  it("project when sites.yml exists", () => {
    const d = tmp();
    fs.writeFileSync(path.join(d, "sites.yml"), "localhost:\n  content_folder: site_x\n");
    expect(detectProject(d).kind).toBe("project");
  });

  it("dirty when unrelated files", () => {
    const d = tmp();
    fs.writeFileSync(path.join(d, "README.md"), "hi");
    expect(detectProject(d).kind).toBe("dirty");
  });

  it("allows .gitignore alone as empty", () => {
    const d = tmp();
    fs.writeFileSync(path.join(d, ".gitignore"), ".env\n");
    expect(detectProject(d).kind).toBe("empty");
  });

  it("needs_sites_yml when site_* dirs exist without sites.yml", () => {
    const d = tmp();
    fs.mkdirSync(path.join(d, "site_acme"));
    fs.writeFileSync(path.join(d, "README.md"), "notes");
    const result = detectProject(d);
    expect(result.kind).toBe("needs_sites_yml");
    expect(result.siteFolders).toEqual(["site_acme"]);
  });

  it("lists multiple site_* folders sorted", () => {
    const d = tmp();
    fs.mkdirSync(path.join(d, "site_z"));
    fs.mkdirSync(path.join(d, "site_a"));
    expect(listSiteFolders(d)).toEqual(["site_a", "site_z"]);
    expect(detectProject(d).siteFolders).toEqual(["site_a", "site_z"]);
  });
});

describe("sitesYmlForEntries", () => {
  it("writes minimal multi-host yaml", () => {
    expect(
      sitesYmlForEntries([
        { domain: "localhost", contentFolder: "site_a" },
        { domain: "b.localhost", contentFolder: "site_b" },
      ]),
    ).toBe(
      `# Generated by weblify CLI
localhost:
  content_folder: site_a

b.localhost:
  content_folder: site_b
`,
    );
  });
});

describe("resolveSitesYmlEntries (non-interactive)", () => {
  function cfg(partial: Partial<ResolvedConfig> & Pick<ResolvedConfig, "detect">): ResolvedConfig {
    return {
      projectRoot: partial.projectRoot ?? "/tmp",
      packageRoot: partial.packageRoot ?? "/tmp",
      isProduction: false,
      wantAgent: false,
      agentChoice: null,
      noMcpTunnel: false,
      command: null,
      yes: false,
      ...partial,
    };
  }

  it("single folder with --yes → localhost", async () => {
    const entries = await resolveSitesYmlEntries(
      cfg({
        yes: true,
        detect: { kind: "needs_sites_yml", root: "/tmp", siteFolders: ["site_acme"] },
      }),
    );
    expect(entries).toEqual([{ domain: "localhost", contentFolder: "site_acme" }]);
  });

  it("multiple folders require --slug when non-interactive", async () => {
    await expect(
      resolveSitesYmlEntries(
        cfg({
          yes: true,
          detect: {
            kind: "needs_sites_yml",
            root: "/tmp",
            siteFolders: ["site_a", "site_b"],
          },
        }),
      ),
    ).rejects.toThrow(/--slug/);
  });

  it("multiple folders + --slug picks that folder", async () => {
    const entries = await resolveSitesYmlEntries(
      cfg({
        yes: true,
        contentSlug: "b",
        detect: {
          kind: "needs_sites_yml",
          root: "/tmp",
          siteFolders: ["site_a", "site_b"],
        },
      }),
    );
    expect(entries).toEqual([{ domain: "localhost", contentFolder: "site_b" }]);
  });
});
